ALTER TABLE [dbo].[UsersInRoles]
    ADD CONSTRAINT [IX_UsersInRolesRoleID] UNIQUE NONCLUSTERED ([RoleID] ASC, [UserID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

