ALTER TABLE [dbo].[IPN]
    ADD CONSTRAINT [PK_IPN] PRIMARY KEY CLUSTERED ([IPNID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

