ALTER TABLE [dbo].[Portals]
    ADD CONSTRAINT [PK_Portals] PRIMARY KEY CLUSTERED ([PortalID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

