ALTER TABLE [dbo].[PortalAlias]
    ADD CONSTRAINT [PK_PortalAlias] PRIMARY KEY CLUSTERED ([PortalAliasID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

