ALTER TABLE [dbo].[StoreVariantTypes]
    ADD CONSTRAINT [PK_StoreVariantTypes] PRIMARY KEY CLUSTERED ([AnswerTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

