ALTER TABLE [dbo].[StoreCartItems]
    ADD CONSTRAINT [PK_StoreCartItems] PRIMARY KEY CLUSTERED ([CartItemID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

