ALTER TABLE [dbo].[SurveyQuestions]
    ADD CONSTRAINT [PK_SurveyQuestions] PRIMARY KEY CLUSTERED ([QuestionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

