ALTER TABLE [dbo].[StoreVariants]
    ADD CONSTRAINT [PK_StoreVariants] PRIMARY KEY CLUSTERED ([VariantID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

