ALTER TABLE [dbo].[SurveyAnswers]
    ADD CONSTRAINT [PK_SurveyAnswers] PRIMARY KEY CLUSTERED ([AnswerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

