ALTER TABLE [dbo].[SurveyAnswerGroups]
    ADD CONSTRAINT [PK_SurveyAnswerGroups] PRIMARY KEY CLUSTERED ([AnswerGroupID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

