ALTER TABLE [dbo].[SurveyAnswersTypes]
    ADD CONSTRAINT [PK_SurveyAnswersTypes] PRIMARY KEY CLUSTERED ([SurveyAnswerTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

