ALTER TABLE [dbo].[SiteLog]
    ADD CONSTRAINT [PK_SiteLog] PRIMARY KEY CLUSTERED ([SiteLogID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

