ALTER TABLE [dbo].[TaxRate]
    ADD CONSTRAINT [PK_TaxRate] PRIMARY KEY CLUSTERED ([TaxRateID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

